### ISSUE TITLE
Script package options do not show XAML forms

### ISSUE THREAD

**Issue by adamdriscoll** [ironmansoftware/poshprotools#14]

**Comment by TessLaCoil** [comment]
Just did an extra check, populating the list seems to break as soon as a WPF form is added.
If you add a PowerShell form first, it will properly add to that to the picklist.
Adding multiple PowerShell Forms is no issue. Seems fully related to the WPF.
Tried up to 3 PowerShell Forms first, but upon adding the WPF/xaml it stops updating the list.

**Comment by TessLaCoil** [comment]
@adamdriscoll I can see the XAML there and the build is working. 
However, when I start the app I'm prompted with this: (made a clean WPF app)
![image](https://user-images.githubusercontent.com/1567234/39550202-cb666d40-4e60-11e8-91c0-18f4805aa8eb.png)

One note btw which might be logical? Is that the .NET Framework Version needs to be set to 4.5.1 otherwise the powershell automation can't be found. (Same when using powershell3.0 from C# project)

![image](https://user-images.githubusercontent.com/1567234/39549773-62677484-4e5f-11e8-805b-2fa9820922dd.png)

![image](https://user-images.githubusercontent.com/1567234/39549837-8b79d3da-4e5f-11e8-9805-643f4d97f3bb.png)

**Comment by adamdriscoll** [comment]
@TessLaCoil Thanks for all the info. 

Can you try and directly launch the exe that was produced here? 

![image](https://user-images.githubusercontent.com/1256531/39550476-06e062c0-4e27-11e8-8c88-26db028726cc.png)

I think the error message pop up is something else. 

I'll open two new issues to check into those things.

**Comment by TessLaCoil** [comment]
Hehe, that one's a bad example locally at home as I don't have the network connection available. 
![image](https://user-images.githubusercontent.com/1567234/39551620-fb69a6ba-4e65-11e8-8868-ed861daaa81e.png)

The clean WPF form (first example) itself from that location is starting properly by double click and commandline execute.
